# The instructions for the first stage
FROM node:10-alpine as builder

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

RUN apk update
RUN apk --no-cache add bash git rsync unison python make g++

COPY package*.json ./
RUN npm install
RUN npm install -g codesandbox

# The instructions for second stage
FROM node:10-alpine

WORKDIR /usr/src/app
COPY --from=builder node_modules node_modules

COPY . .

CMD [ "npm", "start" ]