#!/bin/sh
git --work-tree=/root/second --git-dir=/root/second.git checkout -f
# todo: determine if restart is required for all components, or just server, etc. (what changed in docker-compose, or in nodejs/second?)
cd /root/second && docker-compose -f docker-compose.prod.yml build && docker-compose -f docker-compose.prod.yml down && docker-compose -f docker-compose.prod.yml up -d